# Generated by Django 3.0.2 on 2020-02-15 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome_completo', models.CharField(max_length=60)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('dt_nasc', models.DateField(blank=True, null=True)),
                ('tpLograd', models.CharField(max_length=3)),
                ('lograd', models.CharField(max_length=40)),
                ('num', models.IntegerField()),
                ('compl', models.CharField(max_length=25)),
                ('bairro', models.CharField(max_length=20)),
                ('locali', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
