# Generated by Django 3.0.2 on 2020-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='interesses',
            field=models.CharField(default=['roupas'], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='promos',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
