# Generated by Django 3.0.2 on 2020-02-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0004_auto_20200228_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Adm_Serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
