# Generated by Django 3.0.2 on 2020-02-29 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0005_perfil_adm_serv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_Serv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
                ('user_serv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Perfil_Adm_Serv',
        ),
        migrations.AddField(
            model_name='perfil',
            name='favoritos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
