# Generated by Django 3.0.2 on 2020-03-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0006_auto_20200229_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_serv',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
