# Generated by Django 3.0.2 on 2020-03-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conta', '0007_auto_20200301_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
