# Generated by Django 3.0.2 on 2020-02-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categ_nome', models.CharField(max_length=10)),
                ('principal', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpLograd', models.CharField(max_length=3)),
                ('lograd', models.CharField(max_length=40)),
                ('num', models.IntegerField()),
                ('compl', models.CharField(max_length=25)),
                ('bairro', models.CharField(max_length=20)),
                ('locali', models.CharField(max_length=30)),
                ('cep', models.CharField(max_length=8)),
                ('uf', models.CharField(max_length=2)),
                ('gia', models.CharField(max_length=4)),
                ('unidade', models.CharField(max_length=4)),
                ('ibge', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='HrFuncionamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('horario', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('num', models.CharField(max_length=9)),
                ('wp', models.CharField(max_length=1)),
                ('principal', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario_serv', models.CharField(max_length=8)),
                ('senha', models.CharField(max_length=8)),
                ('email_usuario', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomefantasia', models.CharField(max_length=60)),
                ('razaosocial', models.CharField(blank=True, max_length=60, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True)),
                ('formaspagto', models.CharField(max_length=14)),
                ('tags', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('desc', models.TextField(max_length=200)),
                ('endereco', models.ManyToManyField(to='api.Endereco')),
                ('horario', models.ManyToManyField(to='api.Telefone')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Usuario')),
            ],
        ),
    ]
