# Generated by Django 3.0.2 on 2020-02-12 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='horario',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
