# Generated by Django 3.0.2 on 2020-02-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField(max_length=200)),
                ('id_usuario_consum', models.IntegerField()),
                ('id_servico', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioServ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('usuario_serv', models.CharField(max_length=8)),
                ('senha', models.CharField(max_length=8)),
                ('email_usuario', models.CharField(max_length=60)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=11)),
                ('dt_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='servico',
            old_name='horario',
            new_name='telefone',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_serv',
            new_name='cep',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.ManyToManyField(to='api.Categoria'),
        ),
        migrations.AddField(
            model_name='servico',
            name='nota_media',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servico',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='bairro',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='compl',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2020-02-07'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dt_nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='2020-02-07', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='locali',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='lograd',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='num',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='tel',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tpLograd',
            field=models.CharField(default='R', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='uf',
            field=models.CharField(default='SP', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UsuarioServ'),
        ),
    ]
