# Generated by Django 3.0.2 on 2020-02-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200207_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='telefone',
        ),
        migrations.AddField(
            model_name='telefone',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='api.Servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='nota_media',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=3),
        ),
    ]
