# Generated by Django 3.0.2 on 2020-02-11 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200211_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='endereco',
        ),
        migrations.AddField(
            model_name='endereco',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servico', to='api.Servico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hrfuncionamento',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='servico_horario', to='api.Servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='gia',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='ibge',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='unidade',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='formaspagto',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_telefone', to='api.Servico'),
        ),
    ]
