# Generated by Django 3.0.2 on 2020-03-07 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0002_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.ImageField(blank=True, null=True, upload_to='')),
                ('f2', models.ImageField(blank=True, null=True, upload_to='')),
                ('f3', models.ImageField(blank=True, null=True, upload_to='')),
                ('f4', models.ImageField(blank=True, null=True, upload_to='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagem_servicos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='principal',
        ),
        migrations.AddField(
            model_name='endereco',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servico',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='principal',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='UsuarioServ',
        ),
    ]
