# Generated by Django 3.0.2 on 2020-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0004_auto_20200307_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='desc',
            field=models.TextField(default='Roupas', max_length=60),
            preserve_default=False,
        ),
    ]
