# Generated by Django 3.0.2 on 2020-03-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0005_categoria_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.ManyToManyField(blank=True, null=True, related_name='servico_categ', to='servicos.Categoria'),
        ),
    ]
