# Generated by Django 3.0.2 on 2020-03-08 20:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0006_auto_20200308_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensserv',
            name='f1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='imagem'),
        ),
    ]
