# Generated by Django 3.0.2 on 2020-04-19 20:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicos', '0009_auto_20200419_1553'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favoritos',
            unique_together={('user', 'servico')},
        ),
    ]
