# Generated by Django 3.0.2 on 2020-05-05 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0010_auto_20200419_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='servico',
        ),
        migrations.AddField(
            model_name='servico',
            name='endereco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicos.Endereco'),
            preserve_default=False,
        ),
    ]
