# Generated by Django 3.0.2 on 2020-05-05 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0011_auto_20200505_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagensserv',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='image',
        ),
        migrations.AddField(
            model_name='imagensserv',
            name='servico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imagem_servicos', to='servicos.Servico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servico',
            name='endereco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='servicos.Endereco'),
        ),
    ]
