# Generated by Django 3.0.2 on 2020-05-05 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0012_auto_20200505_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagensserv',
            name='f2',
        ),
        migrations.RemoveField(
            model_name='imagensserv',
            name='f3',
        ),
        migrations.RemoveField(
            model_name='imagensserv',
            name='f4',
        ),
    ]
