# Generated by Django 3.0.2 on 2020-05-05 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0013_auto_20200505_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagensserv',
            old_name='f1',
            new_name='imagem',
        ),
    ]
