# Generated by Django 3.0.2 on 2020-05-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0014_auto_20200505_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensserv',
            name='uri_image',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
