# Generated by Django 3.0.2 on 2020-07-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0015_imagensserv_uri_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='endereco',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='compl',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
